# tooltip displaying info on a single keyword
# generated by KeywordContainer
extends PanelContainer

const TOOLTIP_SIZER_SCRIPT := preload("res://scripts/ui/general/TooltipSizer.gd")

@onready var rich_text_label: RichTextLabel = $RichTextLabel

func init(keyword_object_id: String) -> void:
	var keyword_data: KeywordData = Global.get_keyword_data(keyword_object_id)
	if keyword_data == null:
		push_error("No keyword of id ", keyword_object_id, " found")
	else:
		rich_text_label.parse_bbcode(keyword_data.keyword_text_bb_code)
		TOOLTIP_SIZER_SCRIPT.apply_to(self, rich_text_label, rich_text_label.get_parsed_text())
